require 'simplecov'
SimpleCov.start
# open coverage/index.html in Terminal

require_relative 'customer_repository_spec'
require_relative 'customer_spec'
require_relative 'invoice_item_repository_spec'
require_relative 'invoice_item_spec'
require_relative 'invoice_repository_spec'
require_relative 'invoice_spec'
require_relative 'item_repository_spec'
require_relative 'item_spec'
require_relative 'merchant_repository_spec'
require_relative 'merchant_spec'
require_relative 'sales_analyst_spec'
require_relative 'sales_engine_spec'
require_relative 'transaction_repository_spec'
require_relative 'transaction_spec'

# require './lib/item'
# require './lib/sales_engine'
# require './lib/merchant'
# require './lib/merchant_repository'
# require './lib/item_repository'
# require './lib/sales_analyst'
# require './lib/invoice'
# require './lib/invoice_repository'
# require './lib/invoice_item'
# require './lib/invoice_item_repository'
# require 'date'
# require './lib/transaction'
# require './lib/transaction_repository'
# require './lib/customer'
# require './lib/customer_repository'
# require 'csv'
# require 'BigDecimal'
